### ISSUE TITLE
可否设置单独的一列或者两列的选择

### ISSUE THREAD

**Issue by weilixing00** [alafighting/CharacterPickerView#13]
这个库的效果很不错,谢谢分享,只是需求上需要只选择年份,还有月份和日期,尝试改过,但是效果一般,代码变动挺大.请问能否增加方法只显示单列,或者两列的联动? 目前好像只能三列联动.谢谢!

**Comment by imkarl** [comment]
支持单列、两列、三列，通过控制方法参数个数，可以实现。
建议写一个包裹类来使用，可参考[demo/OptionsWindowHelper.java](https://github.com/ImKarl/CharacterPickerView/blob/master/demo/src/main/java/cn/jeesoft/demo/OptionsWindowHelper.java)
