### ISSUE TITLE
设置默认选中的三级项目无效

### ISSUE THREAD

**Issue by BroganGrow** [alafighting/CharacterPickerView#16]
mOptions.setSelectOptions(0, 0, 0);是有用，但是改变了参数就没用了，第二，第三个参数无效

**Comment by imkarl** [comment]
能说的更详细些吗？或者给份伪代码也行

**Comment by BroganGrow** [comment]
没有啊，你直接设置默认不是非0的位置都是错误的

**Comment by imkarl** [comment]
确实存在这个bug，v0.2.5已修复
[commit/648d3d11](https://github.com/ImKarl/CharacterPickerView/commit/648d3d11c8499bfcfc900a6cc9d8eda6f9d93238)
