### ISSUE TITLE
当只有一级或者二级得时候,字体奇大无比

### ISSUE THREAD

**Issue by nullkk** [alafighting/CharacterPickerView#21]
当只有一级或者二级得时候,字体奇大无比
![1](https://user-images.githubusercontent.com/20369464/41827647-0fc2e104-7863-11e8-9128-897947448ede.png)

**Comment by imkarl** [comment]
升级到v0.2.6，已经限制了字体最大值
你也可以根据需要设置 setMaxTextSize(dpValue)

**Comment by nullkk** [comment]
CharacterPickerView 模式下 有setMaxTextSize , 选择底部弹出 CharacterPickerWindow 模式下 无setMaxTextSize方法...... 能否增加CharacterPickerWindow模式下得setsize  谢谢.辛苦了

**Comment by imkarl** [comment]
v0.2.7 已经加上了

其实，CharacterPickerWindow可以通过getPickerView()拿到CharacterPickerView

**Comment by nullkk** [comment]
工期比较紧张没太仔细看源码😂😂拿来就用了......谢谢博主得开源精神!搞定了!辛苦了,感谢

fix bug

**Comment by imkarl** [comment]
能帮到你就好！   Ψ(￣∀￣)Ψ
