### ISSUE TITLE
BUG！！！！！！！！！！！！！！！！！

### ISSUE THREAD

**Issue by WenYong1994** [alafighting/CharacterPickerView#24]
你的三级联动，在滑动第一个的时候第三个有可能出现数据不一起联动的问题，
出现场景，当第三级滑动到某一个选项时，滑动第二级，有可能会出现第三极的数据不会联动，（几率出现在30%）

**Comment by imkarl** [comment]
最近有点忙，晚几天我再看下。
你有空的，欢迎提PR~

**Comment by imkarl** [comment]
@WenYong1994  已经做了优化，你看下是否还有这个问题。

**Comment by WenYong1994** [comment]
好了。大佬辛苦了
