### ISSUE TITLE
update the CharacterPickerWindow options ?

### ISSUE THREAD

**Issue by cloudshooterhuman** [alafighting/CharacterPickerView#8]
Hey !
I stacked with lib design basically (can't found any way) I need to update the options when I change one of the options.
Any hint about that ?
Regards,
Abdellah

**Comment by imkarl** [comment]
Is it like this?
`characterPickerView.setPicker(options1Items, options2Items, options3Items)`

**Comment by imkarl** [comment]
Using…

> compile 'com.github.imkarl:CharacterPickerView:v0.1'
